name: SimpleSuggestions
version: '${version}'
main: xyz.epicebic.simplesuggestions.SimpleSuggestions
api-version: 1.18
authors: [ Epic ]
website: https://github.com/The-Epic/SimpleSuggestions
libraries:
  - 'com.zaxxer:HikariCP:5.0.1'
  - 'net.dv8tion:JDA:5.0.0-beta.8'
  - 'net.kyori:adventure-platform-bukkit:4.2.0'
  - 'net.kyori:adventure-api:4.13.0'
  - 'net.kyori:adventure-text-minimessage:4.13.0'


commands:
  suggest:
    permission: simplesuggestions.command.suggest
