name: SimpleSuggestions
version: '${version}'
main: xyz.epicebic.simplesuggestions.SimpleSuggestionsPlugin
api-version: 1.18
authors: [ Epic ]
website: https://github.com/The-Epic/SimpleSuggestions
libraries:
  - "net.kyori:adventure-platform-bukkit:4.2.0"
  - "net.kyori:adventure-api:4.13.0"
  - "net.kyori:adventure-text-minimessage:4.13.0"

commands:
  suggest:
    permission: simplesuggestions.command.suggest
  simplesuggestions:
    aliases:
      - suggestions
    permission: simplesuggestions.command
