name: SimpleSuggestions
version: '${version}'
main: xyz.epicebic.simplesuggestions.SimpleSuggestions
api-version: 1.17
authors: [ Epic ]
website: https://github.com/The-Epic/SimpleSuggestions
libraries:
#  - 'com.zaxxer:HikariCP:5.0.1'
