name: SimpleSuggestions
version: '${version}'
main: xyz.epicebic.simplesuggestions.SimpleSuggestionsPlugin
api-version: 1.18
authors: [ Epic ]
website: https://github.com/The-Epic/SimpleSuggestions


commands:
  suggest:
    permission: simplesuggestions.command.suggest
  simplesuggestions:
    aliases:
      - suggestions
    permission: simplesuggestions.command
